Make kiss update scriptable
Continue the upgrade even if kiss itself is upgrade instead of aborting
early. This is achieved by exec-ing into the freshly installed kiss.

The goal of this is to allow `kiss u` to be run as a script and to
always succeed in updating packages given the packages can actually be
accessed and built.

diff --git a/kiss b/kiss
--- a/kiss
+++ b/kiss
@@ -1415,9 +1415,15 @@ pkg_updates() {
         args i kiss
 
         log "Updated the package manager"
-        log "Re-run 'kiss update' to update your system"
+        log "Re-running 'kiss update' to update your system"
 
-        exit 0
+        if ! BIN=$(command -v kiss); then
+            die "Could not find kiss in PATH"
+        fi
+
+        prompt
+
+        exec "$BIN" update
     }
 
     [ "$1" ] || {
